import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#83e881',
        'tertiary-fixed-dim': '#78dc77',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed': '#94f990',
        'on-primary-container': '#cacfff',
        'inverse-surface': '#2e3132',
        'on-tertiary-fixed-variant': '#005313',
        'inverse-on-surface': '#f0f1f2',
        'on-secondary-container': '#653900',
        'surface-dim': '#d9dadb',
        'primary-container': '#3f51b5',
        'on-primary-fixed': '#00105c',
        'surface-bright': '#f8f9fa',
        'on-primary': '#ffffff',
        'tertiary-container': '#00691b',
        'surface-container': '#edeeef',
        'on-surface': '#191c1d',
        'surface': '#f8f9fa',
        'outline': '#757684',
        'secondary-container': '#ff9800',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#ffb870',
        'primary': '#24389c',
        'surface-tint': '#4355b9',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#293ca0',
        'background': '#f8f9fa',
        'secondary': '#8b5000',
        'tertiary': '#004e11',
        'error': '#ba1a1a',
        'on-error-container': '#93000a',
        'secondary-fixed': '#ffdcbe',
        'surface-container-low': '#f3f4f5',
        'on-secondary-fixed': '#2c1600',
        'surface-container-highest': '#e1e3e4',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-variant': '#e1e3e4',
        'primary-fixed-dim': '#bac3ff',
        'on-tertiary-fixed': '#002204',
        'on-surface-variant': '#454652',
        'primary-fixed': '#dee0ff',
        'surface-container-high': '#e7e8e9',
        'inverse-primary': '#bac3ff',
        'outline-variant': '#c5c5d4',
        'on-secondary-fixed-variant': '#693c00',
        'on-background': '#191c1d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['var(--font-plus-jakarta)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
      },
      boxShadow: {
        editorial: '0px 10px 30px rgba(25, 28, 29, 0.06)',
        'editorial-sm': '0px 4px 16px rgba(25, 28, 29, 0.04)',
        'bottom-nav': '0 -10px 30px rgba(25, 28, 29, 0.06)',
      },
    },
  },
  plugins: [],
}

export default config
